name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-kuru-sdk.txt
        
    - name: Check formatting with Black
      run: |
        black --check .
        
    - name: Check imports with isort
      run: |
        isort --check --profile black .
        
    - name: Lint with flake8
      run: |
        flake8 lib tests
        
    - name: Lint with pylint
      run: |
        pylint lib tests
        
    - name: Type check with mypy
      run: |
        mypy lib tests